### PR TITLE
I've added a more or less automatic installer and a .desktop-file for automatic adding to the start menu

### PR DESCRIPTION
**Pull request by NormanTUD**

### CODE REVIEW

**Comment by mgolden** [comment]
Hi NormanTUD - I pulled this in. I also made a change to allow it to support Pop!_os, which is an ubuntu derivative which I use.

One question I have is about the use of /etc/issue as the way of determining what the OS is. I see that it's set up by default, but that file is intended to be edited by the sysadmin, so it might conceivably fail to contain what was put there at install time. Maybe it's better to use one to the methods described here: https://linuxhandbook.com/check-linux-version/ ?

**Comment by mgolden** [comment]
@NormanTUD  I left the @ sign off above!

**Comment by NormanTUD** [comment]
Thanks for pulling this, really like the idea of the tool. And yes, you're right. The most secure way is probably using hostnamectl, or maybe even just looking if apt is installed (which should be sufficient for most tasks I guess). If you're willing to change it, go for it. I may also do it, but it'll take some time until I have leasure time to do it.
Have a nice day
Norman

**Comment by mgolden** [comment]
I like the idea of looking for apt. As you note - that's actually likely to be sufficient, and it doesn't require maintaining a list of debian derivatives, of which there are many.

I might have time in a few days.

The current problem is that the latest version of kdeconnect-cli seems to be broken, at least on kubuntu 20.10, and the tool isn't working for me. I get this error:

/usr/bin/kdeconnect-cli --device 'f31a6d618370e88b' --destination '+1 ***-***-****' --send-sms 'test'

error: No such method 'sendSms' in interface 'org.kde.kdeconnect.device.sms' at object path '/modules/kdeconnect/devices/f31a6d618370e88b/sms' (signature 'ss')

**Pull request merged**
